name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0

      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        
    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

  coverage:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Check coverage
      run: |
        npx nyc report --reporter=json
        coverage=$(cat coverage/coverage-final.json | jq -r '.total.lines.pct')
        
        if [ -n "$coverage" ]; then
          echo "Current Coverage is $coverage%."
          if (( $(echo "$coverage < 90" | bc -l) )); then
            echo "Coverage must be greater than 90%."
            exit 1
          fi
        else
          echo "Could not obtain coverage information."
          exit 1
        fi
