name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0

      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        
    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

  coverage:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0
        
    - name: Install dependencies
      run: npm install

    - name: Run tests and check coverage
      run: |
        npm run test

        npm install -g coverage-percentage

        coverage=$(coverage-percentage coverage/lcov.info)

        echo "Statements Coverage is $coverage."

        if (( $(echo "$coverage < 90" | bc -l) )); then
          echo "Statements Coverage must be greater than 90%."
          exit 1
        fi
