name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0

      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        
    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

   coverage:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0

    - name: Install dependencies
      run: npm install

    - name: Run coverage
      run: npm run test -- --coverage

    - name: Check coverage
      run: |
        coverage=$(grep -oP 'Statements.*?(\d+)%' coverage/summary.txt | awk '{print $2}')
        echo "Current Coverage is $coverage%."
        if [ "$coverage" -lt 90 ]; then
          echo "Coverage must be grater than 90%."
          exit 1
        fi
